
version: '3'

services:
  downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'SoReL20M-downloader'
    tty: true
    volumes:
      - ./:/workspace
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json